### ISSUE TITLE
Failure to run in latest version of React Native and Xcode

### ISSUE THREAD

**Issue by zackha** [Metin-Piskin/MemeMakerApplication#1]
Hi @Metin-Piskin,

I was very interested in this project, although I tried for 2 days, I could not manage to run your project. I wonder if you have the possibility to update this project?

Best Regards,

**Comment by Metin-Piskin** [comment]
Since this application is developed on the Windows operating system, it is necessary to add the necessary library dependencies on the Xcode side

**Comment by Metin-Piskin** [comment]
> Hi @Metin-Piskin,
> 
> I was very interested in this project, although I tried for 2 days, I could not manage to run your project. I wonder if you have the possibility to update this project?
> 
> Best Regards,

Since this application is developed on the Windows operating system, it is necessary to add the necessary library dependencies on the Xcode side
